# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Armaduras.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Armaduras(object):
    def setupUi(self, Armaduras):
        Armaduras.setObjectName("Armaduras")
        Armaduras.resize(1369, 977)
        self.centralwidget = QtWidgets.QWidget(Armaduras)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(40, 0, 300, 45))
        self.frame_3.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(300, 45))
        self.frame_3.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.cb_paginas = QtWidgets.QComboBox(self.frame_3)
        self.cb_paginas.setGeometry(QtCore.QRect(0, 0, 300, 45))
        self.cb_paginas.setMinimumSize(QtCore.QSize(200, 0))
        self.cb_paginas.setMaximumSize(QtCore.QSize(300, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cb_paginas.setFont(font)
        self.cb_paginas.setToolTip("")
        self.cb_paginas.setStyleSheet("QComboBox{\n"
"    /* Borde */\n"
"    border: 2px solid rgb(142, 168, 195);\n"
"    border-radius: 5px;\n"
"\n"
"    /* Color de fondo */\n"
"    background-color:rgb(255, 255, 255); \n"
"\n"
"    /* Color de Letras */\n"
"    color: rgb(100,100,100);\n"
"\n"
"    /* Formato de Letras */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox:hover{\n"
"    /* Borde */\n"
"    border: 2px solid rgb(255, 195, 15)\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.cb_paginas.setEditable(False)
        self.cb_paginas.setObjectName("cb_paginas")
        self.cb_paginas.addItem("")
        self.cb_paginas.addItem("")
        self.cb_paginas.addItem("")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1371, 881))
        self.stackedWidget.setObjectName("stackedWidget")
        self.pag_1 = QtWidgets.QWidget()
        self.pag_1.setObjectName("pag_1")
        self.groupBox = QtWidgets.QGroupBox(self.pag_1)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 1351, 861))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    /* Ancho y color del borde*/\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"\n"
"    /* Radio del borde */\n"
"    border-radius: 10px;\n"
"\n"
"    /* Formato de la letra */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"\n"
"    /*Color de la letra*/\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.tbl_elem = QtWidgets.QTableWidget(self.groupBox)
        self.tbl_elem.setGeometry(QtCore.QRect(10, 76, 541, 192))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tbl_elem.setFont(font)
        self.tbl_elem.setStyleSheet("QTableWidget{\n"
"    /* Color de Fondo de la tabla */\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    /* Formato a las letras en la tabla*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"}\n"
"\n"
"QHeaderView{\n"
"    /* Color de Fondo del encabezado */\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    /* Formato a las letras en la cabeceras*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"")
        self.tbl_elem.setRowCount(0)
        self.tbl_elem.setObjectName("tbl_elem")
        self.tbl_elem.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_elem.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_elem.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_elem.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_elem.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_elem.setHorizontalHeaderItem(4, item)
        self.tbl_elem.horizontalHeader().setVisible(False)
        self.tbl_elem.verticalHeader().setVisible(False)
        self.sp_numElem = QtWidgets.QSpinBox(self.groupBox)
        self.sp_numElem.setGeometry(QtCore.QRect(230, 30, 81, 31))
        self.sp_numElem.setStyleSheet("QSpinBox{\n"
"    /* Borde */\n"
"    border: 2px solid rgb(142, 168, 195);\n"
"    border-radius: 5px;\n"
"\n"
"    /* Color de fondo */\n"
"    background-color:rgb(255, 255, 255); \n"
"\n"
"    /* Color de Letras */\n"
"    color: rgb(100,100,100);\n"
"\n"
"    /* Formato de Letras */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"\n"
"\n"
"\n"
"QSpinBox:hover{\n"
"    /* Borde */\n"
"    border: 2px solid rgb(255, 195, 15)\n"
"\n"
"}\n"
"")
        self.sp_numElem.setAlignment(QtCore.Qt.AlignCenter)
        self.sp_numElem.setObjectName("sp_numElem")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 36, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"\n"
"    /* Color de Fondo*/\n"
"    background-color: None;\n"
"    \n"
"    /* Formato de la letra */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"    /* Color de la letra */\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label.setObjectName("label")
        self.sp_numNodo = QtWidgets.QSpinBox(self.groupBox)
        self.sp_numNodo.setGeometry(QtCore.QRect(740, 32, 81, 31))
        self.sp_numNodo.setStyleSheet("QSpinBox{\n"
"    /* Borde */\n"
"    border: 2px solid rgb(142, 168, 195);\n"
"    border-radius: 5px;\n"
"\n"
"    /* Color de fondo */\n"
"    background-color:rgb(255, 255, 255); \n"
"\n"
"    /* Color de Letras */\n"
"    color: rgb(100,100,100);\n"
"\n"
"    /* Formato de Letras */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"\n"
"\n"
"\n"
"QSpinBox:hover{\n"
"    /* Borde */\n"
"    border: 2px solid rgb(255, 195, 15)\n"
"\n"
"}\n"
"")
        self.sp_numNodo.setAlignment(QtCore.Qt.AlignCenter)
        self.sp_numNodo.setObjectName("sp_numNodo")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(580, 36, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: None;\n"
"    \n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.tbl_nod = QtWidgets.QTableWidget(self.groupBox)
        self.tbl_nod.setGeometry(QtCore.QRect(570, 76, 441, 192))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tbl_nod.setFont(font)
        self.tbl_nod.setStyleSheet("QTableWidget{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    /* Formato a las letras*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"}\n"
"\n"
"QHeaderView{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    /* Formato a las cabeceras*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"")
        self.tbl_nod.setRowCount(0)
        self.tbl_nod.setObjectName("tbl_nod")
        self.tbl_nod.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_nod.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_nod.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_nod.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_nod.setHorizontalHeaderItem(3, item)
        self.tbl_nod.horizontalHeader().setVisible(False)
        self.tbl_nod.verticalHeader().setVisible(False)
        self.sp_fuerzas = QtWidgets.QSpinBox(self.groupBox)
        self.sp_fuerzas.setGeometry(QtCore.QRect(1210, 36, 81, 31))
        self.sp_fuerzas.setStyleSheet("QSpinBox{\n"
"    /* Borde */\n"
"    border: 2px solid rgb(142, 168, 195);\n"
"    border-radius: 5px;\n"
"\n"
"    /* Color de fondo */\n"
"    background-color:rgb(255, 255, 255); \n"
"\n"
"    /* Color de Letras */\n"
"    color: rgb(100,100,100);\n"
"\n"
"    /* Formato de Letras */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"\n"
"\n"
"\n"
"QSpinBox:hover{\n"
"    /* Borde */\n"
"    border: 2px solid rgb(255, 195, 15)\n"
"\n"
"}\n"
"")
        self.sp_fuerzas.setAlignment(QtCore.Qt.AlignCenter)
        self.sp_fuerzas.setObjectName("sp_fuerzas")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(1040, 40, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: None;\n"
"    \n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.tbl_fuerzas = QtWidgets.QTableWidget(self.groupBox)
        self.tbl_fuerzas.setGeometry(QtCore.QRect(1030, 80, 311, 192))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tbl_fuerzas.setFont(font)
        self.tbl_fuerzas.setStyleSheet("QTableWidget{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    /* Formato a las letras*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"}\n"
"\n"
"QHeaderView{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    /* Formato a las cabeceras*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"")
        self.tbl_fuerzas.setRowCount(0)
        self.tbl_fuerzas.setObjectName("tbl_fuerzas")
        self.tbl_fuerzas.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_fuerzas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_fuerzas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_fuerzas.setHorizontalHeaderItem(2, item)
        self.tbl_fuerzas.horizontalHeader().setVisible(False)
        self.tbl_fuerzas.verticalHeader().setVisible(False)
        self.sp_desp = QtWidgets.QSpinBox(self.groupBox)
        self.sp_desp.setGeometry(QtCore.QRect(180, 300, 81, 31))
        self.sp_desp.setStyleSheet("QSpinBox{\n"
"    /* Borde */\n"
"    border: 2px solid rgb(142, 168, 195);\n"
"    border-radius: 5px;\n"
"\n"
"    /* Color de fondo */\n"
"    background-color:rgb(255, 255, 255); \n"
"\n"
"    /* Color de Letras */\n"
"    color: rgb(100,100,100);\n"
"\n"
"    /* Formato de Letras */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"\n"
"\n"
"\n"
"QSpinBox:hover{\n"
"    /* Borde */\n"
"    border: 2px solid rgb(255, 195, 15)\n"
"\n"
"}\n"
"")
        self.sp_desp.setAlignment(QtCore.Qt.AlignCenter)
        self.sp_desp.setObjectName("sp_desp")
        self.tbl_desp = QtWidgets.QTableWidget(self.groupBox)
        self.tbl_desp.setGeometry(QtCore.QRect(10, 340, 311, 192))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tbl_desp.setFont(font)
        self.tbl_desp.setStyleSheet("QTableWidget{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    /* Formato a las letras*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"}\n"
"\n"
"QHeaderView{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    /* Formato a las cabeceras*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"")
        self.tbl_desp.setRowCount(0)
        self.tbl_desp.setObjectName("tbl_desp")
        self.tbl_desp.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_desp.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_desp.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_desp.setHorizontalHeaderItem(2, item)
        self.tbl_desp.horizontalHeader().setVisible(False)
        self.tbl_desp.verticalHeader().setVisible(False)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 290, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: None;\n"
"    \n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 310, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: None;\n"
"    \n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.wgt_armadura = MatplotlibWidgetLienzo(self.groupBox)
        self.wgt_armadura.setGeometry(QtCore.QRect(369, 290, 971, 561))
        self.wgt_armadura.setStyleSheet("/*Color de Fondo*/\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"/* Radio del borde */\n"
"border-radius: 10px;")
        self.wgt_armadura.setObjectName("wgt_armadura")
        self.wgt_restricciones = MatplotlibWidgetLienzo(self.groupBox)
        self.wgt_restricciones.setGeometry(QtCore.QRect(10, 610, 311, 151))
        self.wgt_restricciones.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.wgt_restricciones.setObjectName("wgt_restricciones")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(27, 580, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: None;\n"
"    \n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.btn_visualizar = QtWidgets.QPushButton(self.groupBox)
        self.btn_visualizar.setGeometry(QtCore.QRect(10, 780, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_visualizar.setFont(font)
        self.btn_visualizar.setStyleSheet("\n"
"QPushButton{    \n"
"    /* Color de Fondo */\n"
"    background-color: rgb(64, 110, 142);\n"
"\n"
"    /* Ancho y color del borde */\n"
"    border: 2px solid rgb(142, 168, 195);\n"
"    \n"
"    /* Color de las letras */\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"    /* Radio del borde */\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover{    \n"
"    /* Color de Fondo (al pasar el ratón) */\n"
"    background-color: rgb(142, 168, 195);\n"
"\n"
"    /* Ancho y color del borde (al pasar el ratón) */\n"
"    border: 2px solid rgb(203, 247, 237);\n"
"}\n"
"\n"
"QPushButton:pressed{    \n"
"    /* Color de Fondo (al presionar el botón) */\n"
"    background-color: rgb(203, 247, 237);\n"
"    \n"
"    /* Color de Fondo (al presionar el botón) */\n"
"    border: 2px solid rgb(246, 253, 157);\n"
"}")
        self.btn_visualizar.setObjectName("btn_visualizar")
        self.stackedWidget.addWidget(self.pag_1)
        self.pag_2 = QtWidgets.QWidget()
        self.pag_2.setObjectName("pag_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.pag_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 1351, 331))
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"    /* Ancho y color del borde*/\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"\n"
"    /* Radio del borde */\n"
"    border-radius: 10px;\n"
"\n"
"    /* Formato de la letra */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"\n"
"    /*Color de la letra*/\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(21, 32, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
"\n"
"    /* Color de Fondo*/\n"
"    background-color: None;\n"
"    \n"
"    /* Formato de la letra */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"    /* Color de la letra */\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.cb_elemento = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_elemento.setGeometry(QtCore.QRect(116, 28, 69, 31))
        self.cb_elemento.setMinimumSize(QtCore.QSize(0, 0))
        self.cb_elemento.setMaximumSize(QtCore.QSize(300, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cb_elemento.setFont(font)
        self.cb_elemento.setToolTip("")
        self.cb_elemento.setStyleSheet("QComboBox{\n"
"    /* Borde */\n"
"    border: 2px solid rgb(142, 168, 195);\n"
"    border-radius: 5px;\n"
"\n"
"    /* Color de fondo */\n"
"    background-color:rgb(255, 255, 255); \n"
"\n"
"    /* Color de Letras */\n"
"    color: rgb(100,100,100);\n"
"\n"
"    /* Formato de Letras */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox:hover{\n"
"    /* Borde */\n"
"    border: 2px solid rgb(255, 195, 15)\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.cb_elemento.setEditable(False)
        self.cb_elemento.setCurrentText("")
        self.cb_elemento.setObjectName("cb_elemento")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 321, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel{\n"
"\n"
"    /* Color de Fondo*/\n"
"    background-color: None;\n"
"    \n"
"    /* Formato de la letra */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"    /* Color de la letra */\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_8.setObjectName("label_8")
        self.tbl_MRLE = QtWidgets.QTableWidget(self.groupBox_2)
        self.tbl_MRLE.setGeometry(QtCore.QRect(50, 140, 211, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tbl_MRLE.setFont(font)
        self.tbl_MRLE.setStyleSheet("QTableWidget{\n"
"    /* Color de Fondo de la tabla */\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    /* Formato a las letras en la tabla*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"}\n"
"\n"
"QHeaderView{\n"
"    /* Color de Fondo del encabezado */\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    /* Formato a las letras en la cabeceras*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"")
        self.tbl_MRLE.setRowCount(0)
        self.tbl_MRLE.setObjectName("tbl_MRLE")
        self.tbl_MRLE.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_MRLE.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_MRLE.setHorizontalHeaderItem(1, item)
        self.tbl_MRLE.horizontalHeader().setVisible(False)
        self.tbl_MRLE.verticalHeader().setVisible(False)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(470, 90, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel{\n"
"\n"
"    /* Color de Fondo*/\n"
"    background-color: None;\n"
"    \n"
"    /* Formato de la letra */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"    /* Color de la letra */\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_9.setObjectName("label_9")
        self.tbl_MTE = QtWidgets.QTableWidget(self.groupBox_2)
        self.tbl_MTE.setGeometry(QtCore.QRect(470, 140, 331, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tbl_MTE.setFont(font)
        self.tbl_MTE.setStyleSheet("QTableWidget{\n"
"    /* Color de Fondo de la tabla */\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    /* Formato a las letras en la tabla*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"}\n"
"\n"
"QHeaderView{\n"
"    /* Color de Fondo del encabezado */\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    /* Formato a las letras en la cabeceras*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"")
        self.tbl_MTE.setRowCount(0)
        self.tbl_MTE.setObjectName("tbl_MTE")
        self.tbl_MTE.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_MTE.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_MTE.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_MTE.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_MTE.setHorizontalHeaderItem(3, item)
        self.tbl_MTE.horizontalHeader().setVisible(False)
        self.tbl_MTE.verticalHeader().setVisible(False)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(950, 90, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel{\n"
"\n"
"    /* Color de Fondo*/\n"
"    background-color: None;\n"
"    \n"
"    /* Formato de la letra */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"    /* Color de la letra */\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_10.setObjectName("label_10")
        self.tbl_MRGE = QtWidgets.QTableWidget(self.groupBox_2)
        self.tbl_MRGE.setGeometry(QtCore.QRect(920, 130, 391, 192))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tbl_MRGE.setFont(font)
        self.tbl_MRGE.setStyleSheet("QTableWidget{\n"
"    /* Color de Fondo de la tabla */\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    /* Formato a las letras en la tabla*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"}\n"
"\n"
"QHeaderView{\n"
"    /* Color de Fondo del encabezado */\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    /* Formato a las letras en la cabeceras*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"")
        self.tbl_MRGE.setRowCount(4)
        self.tbl_MRGE.setObjectName("tbl_MRGE")
        self.tbl_MRGE.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_MRGE.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_MRGE.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_MRGE.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_MRGE.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_MRGE.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_MRGE.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_MRGE.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_MRGE.setHorizontalHeaderItem(3, item)
        self.tbl_MRGE.horizontalHeader().setVisible(True)
        self.tbl_MRGE.verticalHeader().setVisible(True)
        self.lbl_LX = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_LX.setGeometry(QtCore.QRect(560, 259, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lbl_LX.setFont(font)
        self.lbl_LX.setStyleSheet("QLabel{\n"
"\n"
"    /* Color de Fondo*/\n"
"    background-color: None;\n"
"    \n"
"    /* Formato de la letra */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"    /* Color de la letra */\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.lbl_LX.setObjectName("lbl_LX")
        self.lbl_LY = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_LY.setGeometry(QtCore.QRect(560, 290, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lbl_LY.setFont(font)
        self.lbl_LY.setStyleSheet("QLabel{\n"
"\n"
"    /* Color de Fondo*/\n"
"    background-color: None;\n"
"    \n"
"    /* Formato de la letra */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"    /* Color de la letra */\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.lbl_LY.setObjectName("lbl_LY")
        self.groupBox_4 = QtWidgets.QGroupBox(self.pag_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 350, 1351, 531))
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"    /* Ancho y color del borde*/\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"\n"
"    /* Radio del borde */\n"
"    border-radius: 10px;\n"
"\n"
"    /* Formato de la letra */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"\n"
"    /*Color de la letra*/\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(140, 67, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel{\n"
"\n"
"    /* Color de Fondo*/\n"
"    background-color: None;\n"
"    \n"
"    /* Formato de la letra */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"    /* Color de la letra */\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_13.setObjectName("label_13")
        self.tbl_MRGA = QtWidgets.QTableWidget(self.groupBox_4)
        self.tbl_MRGA.setGeometry(QtCore.QRect(10, 100, 581, 401))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tbl_MRGA.setFont(font)
        self.tbl_MRGA.setStyleSheet("QTableWidget{\n"
"    /* Color de Fondo de la tabla */\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    /* Formato a las letras en la tabla*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"}\n"
"\n"
"QHeaderView{\n"
"    /* Color de Fondo del encabezado */\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    /* Formato a las letras en la cabeceras*/\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"")
        self.tbl_MRGA.setRowCount(0)
        self.tbl_MRGA.setObjectName("tbl_MRGA")
        self.tbl_MRGA.setColumnCount(0)
        self.tbl_MRGA.horizontalHeader().setVisible(True)
        self.tbl_MRGA.verticalHeader().setVisible(True)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(770, 23, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel{\n"
"\n"
"    /* Color de Fondo*/\n"
"    background-color: None;\n"
"    \n"
"    /* Formato de la letra */\n"
"    font: 75 14pt \"Times New Roman\";\n"
"    \n"
"    /* Color de la letra */\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_14.setObjectName("label_14")
        self.wgt_GL = MatplotlibWidgetLienzo(self.groupBox_4)
        self.wgt_GL.setGeometry(QtCore.QRect(599, 60, 741, 461))
        self.wgt_GL.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.wgt_GL.setObjectName("wgt_GL")
        self.stackedWidget.addWidget(self.pag_2)
        self.pag_3 = QtWidgets.QWidget()
        self.pag_3.setObjectName("pag_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.pag_3)
        self.groupBox_3.setGeometry(QtCore.QRect(170, 230, 120, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.stackedWidget.addWidget(self.pag_3)
        self.verticalLayout.addWidget(self.frame_2)
        Armaduras.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Armaduras)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1369, 22))
        self.menubar.setObjectName("menubar")
        Armaduras.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Armaduras)
        self.statusbar.setObjectName("statusbar")
        Armaduras.setStatusBar(self.statusbar)

        self.retranslateUi(Armaduras)
        QtCore.QMetaObject.connectSlotsByName(Armaduras)

    def retranslateUi(self, Armaduras):
        _translate = QtCore.QCoreApplication.translate
        Armaduras.setWindowTitle(_translate("Armaduras", "MainWindow"))
        self.cb_paginas.setCurrentText(_translate("Armaduras", "INTRODUCIR DATOS"))
        self.cb_paginas.setItemText(0, _translate("Armaduras", "INTRODUCIR DATOS"))
        self.cb_paginas.setItemText(1, _translate("Armaduras", "MATRIZ DE RIGIDEZ"))
        self.cb_paginas.setItemText(2, _translate("Armaduras", "RESULTADOS Y DIAGRAMAS"))
        self.groupBox.setTitle(_translate("Armaduras", "DATOS"))
        item = self.tbl_elem.horizontalHeaderItem(0)
        item.setText(_translate("Armaduras", "Elemento"))
        item = self.tbl_elem.horizontalHeaderItem(1)
        item.setText(_translate("Armaduras", "Area"))
        item = self.tbl_elem.horizontalHeaderItem(2)
        item.setText(_translate("Armaduras", "Mod. Elast."))
        item = self.tbl_elem.horizontalHeaderItem(3)
        item.setText(_translate("Armaduras", "Nodo Inicial"))
        item = self.tbl_elem.horizontalHeaderItem(4)
        item.setText(_translate("Armaduras", "Nodo Final"))
        self.label.setText(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">Número de Elementos:</span></p></body></html>"))
        self.label_2.setText(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">Número de Nodos:</span></p></body></html>"))
        item = self.tbl_nod.horizontalHeaderItem(0)
        item.setText(_translate("Armaduras", "Nodo"))
        item = self.tbl_nod.horizontalHeaderItem(1)
        item.setText(_translate("Armaduras", "Coord. X"))
        item = self.tbl_nod.horizontalHeaderItem(2)
        item.setText(_translate("Armaduras", "Coord. Y"))
        item = self.tbl_nod.horizontalHeaderItem(3)
        item.setText(_translate("Armaduras", "Tipo"))
        self.label_3.setText(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">Número de Fuerzas:</span></p></body></html>"))
        item = self.tbl_fuerzas.horizontalHeaderItem(0)
        item.setText(_translate("Armaduras", "Fuerza"))
        item = self.tbl_fuerzas.horizontalHeaderItem(1)
        item.setText(_translate("Armaduras", "Nodo"))
        item = self.tbl_fuerzas.horizontalHeaderItem(2)
        item.setText(_translate("Armaduras", "Dirección"))
        item = self.tbl_desp.horizontalHeaderItem(0)
        item.setText(_translate("Armaduras", "Despla."))
        item = self.tbl_desp.horizontalHeaderItem(1)
        item.setText(_translate("Armaduras", "Nodo"))
        item = self.tbl_desp.horizontalHeaderItem(2)
        item.setText(_translate("Armaduras", "Dirección"))
        self.label_4.setText(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">Número de</span></p></body></html>"))
        self.label_5.setText(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">Desplazamientos:</span></p></body></html>"))
        self.label_6.setText(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">Tipo de Restriccion en los nodos</span></p></body></html>"))
        self.btn_visualizar.setToolTip(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">VISUALIZAR ARMADURA</span></p></body></html>"))
        self.btn_visualizar.setText(_translate("Armaduras", "VISUALIZAR ARMADURA"))
        self.groupBox_2.setTitle(_translate("Armaduras", "Datos por Elemento"))
        self.label_7.setText(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">Elemento:</span></p></body></html>"))
        self.label_8.setText(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">Matriz de Rigidez Local del Elemento:</span></p></body></html>"))
        item = self.tbl_MRLE.horizontalHeaderItem(0)
        item.setText(_translate("Armaduras", "a"))
        item = self.tbl_MRLE.horizontalHeaderItem(1)
        item.setText(_translate("Armaduras", "b"))
        self.label_9.setText(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">Matriz de Transformación de Elemento:</span></p></body></html>"))
        item = self.tbl_MTE.horizontalHeaderItem(0)
        item.setText(_translate("Armaduras", "a"))
        item = self.tbl_MTE.horizontalHeaderItem(1)
        item.setText(_translate("Armaduras", "b"))
        item = self.tbl_MTE.horizontalHeaderItem(2)
        item.setText(_translate("Armaduras", "c"))
        item = self.tbl_MTE.horizontalHeaderItem(3)
        item.setText(_translate("Armaduras", "d"))
        self.label_10.setText(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">Matriz de Rigidez Global del Elemento:</span></p></body></html>"))
        item = self.tbl_MRGE.verticalHeaderItem(0)
        item.setText(_translate("Armaduras", "New Row"))
        item = self.tbl_MRGE.verticalHeaderItem(1)
        item.setText(_translate("Armaduras", "New Row"))
        item = self.tbl_MRGE.verticalHeaderItem(2)
        item.setText(_translate("Armaduras", "New Row"))
        item = self.tbl_MRGE.verticalHeaderItem(3)
        item.setText(_translate("Armaduras", "New Row"))
        item = self.tbl_MRGE.horizontalHeaderItem(0)
        item.setText(_translate("Armaduras", "New Column"))
        item = self.tbl_MRGE.horizontalHeaderItem(1)
        item.setText(_translate("Armaduras", "New Column"))
        item = self.tbl_MRGE.horizontalHeaderItem(2)
        item.setText(_translate("Armaduras", "New Column"))
        item = self.tbl_MRGE.horizontalHeaderItem(3)
        item.setText(_translate("Armaduras", "New Column"))
        self.lbl_LX.setText(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">Lambda X: 0.9581</span></p></body></html>"))
        self.lbl_LY.setText(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">Lambda Y: 0.8456</span></p></body></html>"))
        self.groupBox_4.setTitle(_translate("Armaduras", "Datos de la Estructiura"))
        self.label_13.setText(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">Matriz de Rigidez Global de la Armadura:</span></p></body></html>"))
        self.label_14.setText(_translate("Armaduras", "<html><head/><body><p><span style=\" font-weight:600;\">Grados de Libertad Asignados a cada Miembro:</span></p></body></html>"))
        self.groupBox_3.setTitle(_translate("Armaduras", "GroupBox"))
from UI_MatPlotLib_PyQt5 import MatplotlibWidgetLienzo
